travis:
  secure:
    BINSTAR_TOKEN: NRkS2ugCN2ZYJml/XnjGMXYU5c+hIhSM2NvlzE4qDDBRfcQkYWKDJptlrP23xR1cgu2Qu33KmnOi3sLY0eOPycP9fvN20kC+Ag1NK+BXiWrEwn5cJubL0ce/qiAck8k2GtqKK/nhAlAWaCR9pJV8+mF47anyFtJbEO35QmA9okRAhQeuPJ8nMbFdHwPmPHBtdbhUemOvr0aw2ns5DH9BzSjzNHjFJco+Y2teDtGymE8v17v0QzM0o9PLYddJtrzkWWe+0Vh/hToLV2iesiGR+3NH6VE2NQObvEV2KBbC8Pt+RzuH/Tb5zzyl2Hkr9ARJBRj9XgsAVXdXRmcyWelUt9Bhsc51tG4vcjNYqvVQMp+0tdDjKMU2dr/R9P/5xXkrfGDNvZr5BhZZKz5Z+KM/qPZCjTt4LxWOEQTRHpTsD8Bdd4orGolqLSRrWZo4sFd5FOd/sNeDjypIhCfD4jjnWh9H6FAJlxPWka4labc8Xr6CCq5JdAi4nJ923Oo0eRfEDDuS6K54ihfNgjejEo1l2koMQjQ1OS+YK4I4LT25GGfhBOyGlRcGqSEbS8ORee22tvslJY6gJhamQCt6FDV6Y14TRYPIhsZJ7SpJWiVlIPPAYGKWVrNtSLgJLtq/DE/oOtjXc9h9Gzld76wzwY5r0xhUtqP0s2e190MKwdOR/Zo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
