travis:
  secure:
    BINSTAR_TOKEN: RUMSKcS8NWsab7XDpHxXJcAJFcfbNEJubEvGtQQbe4wwgRCW6n65aWZucW00mvsgNGUiwdKRpAMfXZOZMh6pdadMSDLrDbcbCSMO8D6X54dkEkY+3avIRhnvPEGQ8jqpREfz7r8ntNUCCpXXwpwo9a0/Rrz0u/4foPnUT7N1Zo7keA/WFy5Ax8Mb21rLHTD4E96co6foJx1BDsOEC3vD+tzQTnUnMnXVbTBxiF9YldqGSVzjc9GkaD0NAu8xXe57UPcwARnaAh63UNxEzkmip4eDS/2qy9VvS5+j301QU8IE261G50EEoVkd00dX4mS8wWYBm8nfuuj4OHHyBcClB0B8HlJwxGApbwx8f8HiyxHBzGcCOQCzJqLiQvHeM3u3d2rpbbN140N4QdIe+J2h/y0DK7DcSp1Yf4jNlMNc5/X0M18f6M9AgQ+c5wKLVOzwFl4YAuKKCDSHR44YsFduT5a4M7o8jFPwR8pQ6kB2BYsKmYYqGFbzbLYnHnKeMc8X0cieHyKKA+r2mTPYkynuBBNyUQaA0m35mfIXHqJjbZU/tvmaHVujxqxuIBDtWirnqK/R9OH5yYB6tEcC+uQSChOKP5UDKmzqxq2Bt24h2cUaBgV3gwqHcO1Db8AsxvlhjcDK/uXmDA3dMyrYFl7cVCLBaLIQsnVwNwfuQ1ggC94=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
