travis:
  secure:
    BINSTAR_TOKEN: LOEATx2ceiFlTBo0/7+P63ycDiyZR/t3PuH+y12ea/nfw1kf+jHGWJF9azcS8dSwtczA3A938/KPlZNtuGxUDkGZPevgKvPSvmmwLyr9m5O/MTIRJViVz56JN+63SAdWPhtIiaS6nKnX4XCohbTNonIvRsnEbww4Gq0mBaceo1vZL3XeZtXaAIZU/p1ptWcPPiBPEIrA6ZMlgR7jEJPj3ojUV556jNuP6jjbeMecn9YrcitPzq3s3kiYTCeatgC83F7wFw04DH31VHcXAL3QlRKcrYO5rGINg0AtzuCSFiUxkM8nbVOOaNdKxc+8ViTPBtXUzFFq9Inl3qcu/9Aio1VNqgT2S3cSKVYJK/1nkxa0Ubs4HkIOBEU1GqV006dXBlrW6cQ1PMKoy6vRlMbVFMSTVSsDgFuPBsmYkvwVtPc9QZIdHcRamepMLNiSSD7i54w10LLy/oj+JMNaHe9/1WeEYWhYFTG88hv+3vepwVaRXxN/12V4mWg624NC0J4JeWan2IhQ6ONw1vBajYeqXNy1mgw5z5g5IilZtoEmuUmpaDBSUjUrGhUFNoHXl3Pvo+EmZo6590bhFOSbLo6wx2tZWHNKvyjon73qpCS44j7KgnNelXm2WllEPaD8/VToj9sSHI9nPecKW+0TX8iIo/mCys2vOFtQIr3VVQwfqCU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
